package reason

const fileTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: {{ .File.InputPath }}

{{ if isOfFileType . }}
{{ range .AllMessages -}}
module {{ simpleName . }}Validators = {
	{{- template "msg" . -}}
}
{{ end }}
{{ end }}
`
