package ocaml

const fileTpl = `
(************************************************)
(*       AUTOGENERATED FILE - DO NOT EDIT!      *)
(************************************************)
(* Generated by: protoc-gen-validate            *)
(************************************************)
(*
  Source: {{ .File.InputPath }}
*)


{{ if isOfFileType . }}
module {{ classNameFile . }}Validator = struct
	type 'a result =
		| Ok of 'a
		| Error of string;


	{{ range .AllMessages -}}
		{{- template "msg" . -}}
	{{- end }}

{{ end }}
`

// {{- range .AllMessages -}}
// 	{{"\n"}}
// 	type t = {
// 		{{- range .NonOneOfFields }}
// 			{{ $f := (context .).Field }}{{ $r := (context .).Rules}}
// 		{{ end}}
// 	}
// 	{{- end}}
