package ocaml

const fileTpl = `
(************************************************)
(*       AUTOGENERATED FILE - DO NOT EDIT!      *)
(************************************************)
(* Generated by: protoc-gen-validate            *)
(************************************************)
(*
  Source: {{ .File.InputPath }}
*)


{{ if isOfFileType . }}
module {{ classNameFile . }}Validator = struct
	type 'a t = {
		value: 'a;
		validate: 'a -> bool;
	}

	type validated_field_type =
		| Ok
		| Error of string;
	
	type validated_fields_type = {
		{{- range .AllMessages }}
			{{- range .Fields}}
		{{.Descriptor.Name}}: validated_field_type;  
			{{- end}}
		{{- end}}
	}

	let validate () = {
		{{- range .AllMessages }}{{- range .Fields}}
		{{.Descriptor.Name}}: ;  
		{{- end}}{{- end}}
	}

{{ end }}
`

// {{- range .AllMessages -}}
// 	{{"\n"}}
// 	type t = {
// 		{{- range .NonOneOfFields }}
// 			{{ $f := (context .).Field }}{{ $r := (context .).Rules}}
// 		{{ end}}
// 	}
// 	{{- end}}
